name: Release Version

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'tiki_build'
        
    - uses: actions/checkout@v2
      with:
        repository: 'premake/premake-core'
        path: 'premake5'
    
    - name: Build Premake
      run: |
        cd premake5
        make -f Bootstrap.mak linux 
        cp premake5 ../tiki_build
        cd ..

    - name: Generate script
      run: premake5 --file=scripts/premake5.lua release
